### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by marksmeets** [jimmoores/quandl4j#5]
Hi, happy user of quandl4j here...

My application requests data at startup, and usually this is the same data as in a previous session. It delays startup and causes unnecessary data queries. Caching would be a solution. I plan to extend SessionBuilder with something like withCacheDir(String) to point to a directory where raw data from quandl is put. Furthermore, add  DataSetRequest.Builder.withRetentionPolicy(RetentionPolicy)

A RetentionPolicy is then something to describe when you consider data to be too old. An example of a RetentionPolicy called Day could be something that implies that if the cached data is absent or of a different date than today, data will be fetched from quandl. Otherwise, the cached data is used. Other implemententations could be Week, Month (with their obvious meanings), and WeekDay. WeekDay will consider the cached data up to date if it was downloaded today, or, if today is a Saturday or Sunday, the data was downloaded last Friday.

What do you think of this approach, and are you interested in the code?

Regards,

Mark Smeets.

**Comment by armdev** [comment]
Hi Mark,

I am just follow quandl4j :)

One question: why are you not just use some cache frameworks? Like Ehcache?
http://ehcache.org/

Best Regards,

Armen

**Comment by marksmeets** [comment]
Short answer: I didn't know it existed :-)

I'll have a look!

**Comment by marksmeets** [comment]
Ehcache was a bit overwhelming to me, so I went ahead and coded a small caching layer myself. If interested, I'll happily share.

**Comment by jimmoores** [comment]
Hi, sorry for the delay in getting back to you. If you submit a pull request I'll look at merging in your changes.
Many Thanks,
Jim

**Comment by jimmoores** [comment]
@marksmeets I've had to move the caching stuff onto a branch for now because I've realised it doesn't work correctly. The code assumes that the request is always the same, but if you vary dates, frequency, transforms or anything you'll get the wrong result back.  There wasn't any trivial way to fix it and I urgently needed to do a release because Quandl are deprecating HTTP for HTTPS tomorrow.  If you fancy fixing it, let me know and i'll consider merging it back in.  If not I'll probably take a look at it at some point.

**Comment by marksmeets** [comment]
Hi Jim, never thought about that. For my modest requirements the current 
solution works well, but you're right that kind of usage would mess 
things up. I think the solution would be to encode dates,frequency and 
transforms into the filename. Or maybe use the entire query as filename.

**Comment by jimmoores** [comment]
I thought about that, but you then run into the problem of potentially
returning stale results the following day if someone asks for the complete
date range (it's an identical query string but without the latest result).
There are a bunch of corner cases like that, which is why I parked it on
the branch for now.
